### ISSUE TITLE
Bug disappears from bug section when changing the Testing Done section

### ISSUE THREAD

**Issue by surfjungle** [jjst/rbautofillbug#1]
In a draft code review item, when filling out the "Testing Done" section and clicking "OK" on that section for the first time the bug listed in the "Bugs:" section disappears. A subsequent change to the "Testing Done" section followed by a click of the same section's "OK" button reinstates the bug.

**Comment by jjst** [comment]
I was able to reproduce on a git repo. It doesn't seem to happen on a Mercurial repo.
